### ISSUE TITLE
Grunt-dr-svg-sprties package not working - Unpublished

### ISSUE THREAD

**Issue by Harishm04** [drdk/grunt-dr-svg-sprites#52]
Hi Team,

We are using the **grunt-dr-svg-sprites** package in our application development. When we tried to run Travis build we are getting error as "npm ERR! 404 Not Found - GET https://registry.npmjs.org/grunt-dr-svg-sprites/-/grunt-dr-svg-sprites-1.0.0.tgz - Not found". When we looked for this error we found that **grunt-dr-svg-sprites** package has been unpublished from the npm.

Could you please help in republishing the package.

Thanks,
Harish M.

**Comment by phloe** [comment]
Removing the sole npm account that had published it resulted in this; I was under the wrongful impression that npm would just deprecate the package and not just fully delete them 😳

So sorry this is effecting you.

But while unintended - I would suggest that you perhaps find another solution that is still under active development - if you still need svg sprites at all.
A lot has happened in browsers since this repo was last updated - let alone created 🙂
